site_name: Inferring Sleep Stages in Drosophila Melanogaster with Ethoscope Data and Machine Learning
site_url: http://msc.bc.ic.ac.uk/~mz5318
nav:
    - Abstract: index.md
    - 1. Introduction: introduction.md
    - 2. Data & Methods: methods.md
    - 3. Results: results.md
    - 4. Discussion: discussion.md
    - 5. Conclusion & Future Work: conclusion.md
    - Ethical Considerations: ethics.md
    # - Acknowledgements: acknow.md


theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue grey
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: fontawesome/solid/microscope
    admonition:
      <type>: <icon>
      example: octicons/beaker-16
  features:
    - content.tooltips


copyright: Copyright &copy; 2022 Meng Zhang

extra:
  social:
    - icon: material/linkedin
      link: https://www.linkedin.com/in/meng-zhang-293b6a194/
      name: linked
    - icon: material/github
      link: https://github.com/cleozhangk6

extra_css:
  - stylesheets/extra.css
      

markdown_extensions:
  - abbr
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - md_in_html
